### ISSUE TITLE
Notify on bad download

### ISSUE THREAD

**Issue by elmero1** [caronc/nzb-notify#12]
I use NZBGet and the nzbToMedia Scripts. With this my failed download handling works, but when a download failed, then the status is not failed, rather bad. It's possible to send a notification on bad status?

**Comment by caronc** [comment]
What type of notification are you using (email, slack, Kodi, Telegram, etc)?

On a side note: Make sure you have the _OnFailure_ option turned on (in Notify Scripts settings through NZBGet).

Are any notifications working at all?

**Comment by elmero1** [comment]
I use the prowl notification. The OnFailure options is enabled. Before I added the nzbToMedia scripts. i was notified about the failed downloads. The failed downloads had the status failed. Now with the nzbToMedia script, the status is not failed, it's bad. And with this status i don't receive a notification.

**Comment by caronc** [comment]
You can change the order to which the scripts are called in.  Try processing the Notify script 'before' the nzbToMedia scripts to see if that makes a difference.

Another thing you can optionally do too if you like is turn on _Debug_ mode with the NZB-Notify script and send me the logs (lead2gold@gmail.com).  Maybe there is something in there i can spot and help determine if it's a bug or not.

**Comment by elmero1** [comment]
I changed the order and now it works! Great. Thank you for your help.
