### ISSUE TITLE
Synology + Sabnzbd not working

### ISSUE THREAD

**Issue by Dediqated** [caronc/nzb-notify#14]
I have been trying to make this script work on my Synology NAS with Sabnzbd but it keeps failing. 
I copied the folders `Notify` and `patches` and the files `Notify.py` and `sabnzbd-notify.py` to the scripts folder of sabnzbd with 777 permissions (just to be sure). 

What I've tried:
- Check Enable notification script in sabnzbd, select sabnzbd-notify.py and fill in all kinds of combinations as parameters; fails with `Notification script returned exit code -1 and output "Cannot run script /usr/local/sabnzbd-testing/var/scripts/sabnzbd-notify.py"` if i click on test notification

- Call the `sabnzbd-notify.py` script myself: `python sabnzbd-notify.py complete 'Hello' 'World' tgram://botid/chatid`; fails with 
```
2017-01-12 21:17:47,326 - sabnzbd-notify - 14456 - ERROR - The engine /volume1/@appstore/sabnzbd-testing/var/scripts/Notify.py was not found!
```

- Finally I tried to run the Notify.py script itself: `python Notify.py -s tgram://botid/chatid-t "hello" -b "world"`, after a few seconds it fails with the following message:
```
Traceback (most recent call last):
  File "Notify.py", line 290, in <module>
    from pnotify import *
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/pnotify/__init__.py", line 26, in <module>
    from NotifyBoxcar import NotifyBoxcar
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/pnotify/NotifyBoxcar.py", line 23, in <module>
    import requests
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/requests/__init__.py", line 53, in <module>
    from urllib3.contrib import pyopenssl
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/volume1/@appstore/sabnzbd-testing/var/scripts/Notify/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'
```

The NAS is a DS415+ with DSM version DSM 6.0.2-8451 Update 7.
Running `python -V` gives Python 2.7.12

**Comment by caronc** [comment]
Your error appears to be the same as #13 .

This issue has been resolved in the Main branch ([quick link](https://github.com/caronc/nzb-notify/archive/master.zip)).  But you've given me good incentive to make an official release soon since the issue seems to be hitting others too.

Download the master branch copy and let me know how it goes.

**Comment by Dediqated** [comment]
That's the point, I have been working with the latest version of the master branch, I just downloaded it for the first time yesterday.. The files in the zip you linked don't work either.

**Comment by caronc** [comment]
The first thing we need to solve is this one:
`AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'`

Specifically see [this comment on the ticket](https://github.com/caronc/nzb-notify/issues/13#issuecomment-267824911)

In short, You probably have a bad copy of pyOpenSSL (v16.1.0).  See if you can upgrade your pyOpenSSL package on your NAS to v16.2.0 or higher.

**Comment by caronc** [comment]
@Dediqated: Hey, it's been a week now; I just wanted to follow up on the status of your issue. Did you have a chance to update pyOpenSSL yet? I'm holding off creating an official release until I hear your results (just in case there is any last minute tweaking I may need to do). Please keep me posted.

**Comment by caronc** [comment]
I'm going to close this issue due to lack of response, but please feel free to contact me again if you need to.
