### ISSUE TITLE
Documentation should include usage

### ISSUE THREAD

**Issue by lunarboy** [caronc/nzb-notify#16]
Hello, as a newbie, I do not understand how to actually use the script. I've read the Readme file over and over again, but at no point can I find how to actually enable services. For example, I'm trying to enable a Slack notification for my SABnzbd install. Here's what I did:

1. Installed the script (Notify.py, sabnzbd-notify.py, Notify) in SABnzbd/scripts
2. Tried this in the command line: `python sabnzbd-notify.py complete 'Hello' 'World' slack://TokenA/TokenB/TokenC/#Channel` and it worked.
2. Edited Notify.py to include my Slack webhook tokens: `slack://TokenA/TokenB/TokenC/#Channel` without the `#` at the beginning of the line
3. Added sabnzbd-notify.py as a post-processing script

Received this error:
`2017-05-03 00:08:19,812 - sabnzbd-notify - 9063 - ERROR - Invalid <Type> specified (argument 1)
Syntax: sabnzbd-notify.py <Type> <Title> <Message> url1[,url2[,urlN]]`

I'm not entirely confident that I added that Slack URL correctly. It's right below the Slack section in the Notify.py file, without the # .

Thank you very much!

**Comment by caronc** [comment]
Ah,
It sounds like you're​ very close. To start, you might want to undo any changes you made to the notify.py script. That part isn't necessary.

From your description, I presume you're​ trying to make this work with SABnzbd. So if you got it working from the command line, you're 90% of the way there!

Just take the URL that you made work (slack://TokenA/TokenB/TokenC/#Channel) and specify it as the argument in SABnzbd.  Secondly, make sure SABnzbd is pointing at sabnzbd-notify.py (and not Notify.py). It should just work for you then.

Good luck! Let me know if you get stuck!

**Comment by lunarboy** [comment]
Thank you!

Yes, I have SABnzbd pointing to sabnzbd-notify.py as the post-processing script. But unfortunately I don't know where to put the argument. In the SABnzbd UI there is no place to put an argument.

**Comment by caronc** [comment]
Have a look at [this blog entry I wrote a while ago](http://nuxref.com/2016/10/20/sabnzbd-installation-centos-7/). Maybe it'll explain the setup better. I realize It focuses on CentOS 7 to which you might not be running, but the notify script setup has a screen shot that might help you out. That part is the same no matter what OS you're using (Microsoft, Linux or Macintosh).

**Comment by lunarboy** [comment]
OK, I finally understand! Thank you.

I think it would be helpful for new users if you document in your Readme that in Settings > Notifications…
- Check _Enable notification script_
- Choose _sabnzb-notify.py_ from the Script dropdown menu
- In Parameters, enter the service URL, e.g. slack://TokenA/TokenB/TokenC/#Channel

Thanks so much for making this script and for your help!

**Comment by caronc** [comment]
I appreciate your feedback! I'm away from easy access to update the GitHub documentation at the moment, but I will definitely update it and accommodate your suggestions when I can (hopefully by Sunday at the latest).

In the meantime, I'm glad to see that you got everything working for you!

**Comment by caronc** [comment]
I'll close this issue now; but please feel free to comment or re-open this if you don't feel the changes were satisfactory.  Thanks again for your feedback!
