### ISSUE TITLE
Sending alerts to private DM in Slack

### ISSUE THREAD

**Issue by bshifflett** [caronc/nzb-notify#18]
is there a way to send the notification to a DM in Slack instead of a public channel? or even a private channel? I don't want everyone to see my Plex Notifications.

**Comment by caronc** [comment]
[In the chat API documentation for Slack](https://api.slack.com/methods/chat.postMessage) it says:
> Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name.

But in short: the answer is yes; just specify your private channel in the slack URL: 

- slack://botname@TokenA/TokenB/TokenC/**MyPrivateChannel**

I'm just experimenting with a few things that can't make the code any worse if it doesn't work..  But i added support for @ ... You could try and see if you put your slack username here if it would work (no promises though):

- slack://botname@TokenA/TokenB/TokenC/**@YourUserOnSlack**

I also added support for the Encoded ID too (if you know it).

- slack://botname@TokenA/TokenB/TokenC/**+Encoded_ID_Of_Channel**

You'll have to download this test version from the [master branch here](https://github.com/caronc/nzb-notify/archive/master.zip) if you want to try out the **@** or **+** items.

**Comment by caronc** [comment]
I have not heard back from you in about a month.  I will close this ticket at this time; but feel free to bring any news forth and i'll re-open it if necessary.
