### ISSUE TITLE
Notify.py trunctates Telegram ChatID

### ISSUE THREAD

**Issue by DePingus** [caronc/nzb-notify#28]
Hi. I'm using Telegram and my ChatID is 14 characters long (including the starting minus sign). I tested my bot APIkey and this 14 character ChatID with curl it works fine. But when I run Notify.py either from nzbget or the command line using:

`python ./Notify.py -s tgram://XXXX:XXXX/-1234567890123 -t "Testing" -b "Hello World"`

I get:

`Failed to send Telegram:-1234567890 notification: (400) Bad Request: chat not found.`

In the error message you can see the ChatID is only the first 11 characters of what I wrote in the command line (obviously I'm using a fake ChatID in these examples but I think you get the gist). I get the same error message in nzbget.

Thanks for taking the time!

**Comment by caronc** [comment]
I bumped the limit up. I'm not quite sure i fixed it at 10 characters when i first wrote the plug-in;  sorry about that :blush:.

Give it another go and let me know (you'll need to check out the master branch)

**Comment by DePingus** [comment]
Wow. Awesome! Thank you so much for the quick fix. It works perfectly.
