### ISSUE TITLE
NZBGet Telegram not sending notifications

### ISSUE THREAD

**Issue by jaaacck** [caronc/nzb-notify#30]
When I send a message to my Telegram bot via the curl command everything works fine. The bot sends the message in the chat.

Also, within NZBGet when running the Notify 'Test Server Configuration' I get a message in the Telegram group chat saying the following:

```
NZBGet-Notify Configuration Test
## NZBGet-Notify Configuration Test ##
- **OnFailure**: Yes
- **OnSuccess**: Yes
- **Include Statistics**: Yes
- **Include File Listings**: Yes
- **Include Log Details**: Yes
```

Whenever a download occurs and completes I get no notification. Nothing is showing up in the NZBGet logs either.
All permissions in the script folder are setup correctly. 775 for every file/folder and assigned to the same groups/users as NZBGet is.

I am currently running Centos 7 with Python 2.7.5.
Any pointers on where I am making some amateur mistake?

**Comment by caronc** [comment]
If the test option works from the settings; you're about 90% of the way there! That last 10% seems like you just haven't told NZBGet to call it when you want. From within NZBGet's settings from the **Extension Scripts** option, just add it to the calling list.
![extensions](https://user-images.githubusercontent.com/850374/31208915-dc5978fa-a955-11e7-92f6-6f805419912e.png)

**Comment by caronc** [comment]
Did you end up figuring this out?

**Comment by jaaacck** [comment]
Hi Caronc,

I must have closed the tab and not pressed the reply button!
This did the trick. I knew it would be something simple.

I appreciate the speedy reply even when this one from me wasn't.
