### ISSUE TITLE
SABnzbd error.

### ISSUE THREAD

**Issue by Mathurian** [caronc/nzb-notify#33]
I'm getting an error when trying to run sabnxbd-notify.py, either using SAB itself or attempting to test using CLI. The error is actually in Notify.py, on line 1055. "except TypeError, e:" at the comma apparently. It is showing an invalid syntax. ~I'll attach a screenshot as well~.

**Comment by caronc** [comment]
This is a silly mistake on my part.  Thank you for reporting it!  Try checking out [the master branch](https://github.com/caronc/nzb-notify/archive/master.zip) and you should be good to go.

**Comment by Mathurian** [comment]
That worked...but now I'm getting another one...an ImportError on line 345.


![nzb-notify importerror](https://user-images.githubusercontent.com/34145134/33461943-5e7fbdaa-d5fa-11e7-8b63-8e9e319f1428.jpeg)

**Comment by caronc** [comment]
That's a weird one, _urllib_ is part of python.

What version of python are you running? Make sure you're using v2.7 (3.x won't work).

You could type **python -V** to find out.

**Comment by Mathurian** [comment]
That's probably going to be the issue then. I'm running the latest 3.x. I'll get 2.7 installed and go from there. Thanks for the help so far!

**Comment by Mathurian** [comment]
That got it! Thank you!

**Comment by caronc** [comment]
glad to hear! 😄
