### ISSUE TITLE
[Feature Request] Discord support.

### ISSUE THREAD

**Issue by danjames92** [caronc/nzb-notify#35]
Would be nice. 👍

**Comment by caronc** [comment]
Check out the [master](https://github.com/caronc/nzb-notify/archive/master.zip) and have a go at it.

It's documented [here](https://github.com/caronc/apprise/wiki/Notify_discord) on how to do the syntax.  But basically you just need to setup a webhook (associated with a channel) and build your url from there.

From the command line i was successful doing the following:
```bash
# tts = Text-To-Speech / by default this is off, but for testing it's kind of fun to enable.
#
# The "Websocket_ID" and "Websocket_Token" below is in the format:
#  discord:/Websocket_ID/Websocket_Token?tts=True
#
# You can override the bot name (from it's default) if you specify it on the command
# line too. It uses whatever name you set up if you don't specify it
 ./Notify.py -s discord://override_bot_name@417565656656565298/JHZ7lQml27hghghC1o33Myghghgv7YTpadV_js?tts=True

``` 
I'd be interested in your feedback; let me know if i can close this ticket too! :smile:

**Comment by caronc** [comment]
It's been a week, I'm going to close this issue since it's been completed. But feel free to reach out if you have any other questions or problems!

**Comment by danjames92** [comment]
Works great! Thanks!

**Comment by caronc** [comment]
Add ```?avatar=Yes``` to the end of your URL and you should be good to go! :smile:

**Comment by danjames92** [comment]
@caronc I'd love to be able to point to a public image online and use that as the avatar. 👍
