### ISSUE TITLE
No notifications [Pushover]

### ISSUE THREAD

**Issue by CastawayEngineer** [caronc/nzb-notify#4]
I'm running nzbget 17.0-testing-r1726 on CentOS 6.8 and installed nzbget-notify and nzbget appears to not be sending notifications at all. 

I have debugging enabled, but do not see anything related in the main nzbget.log file.

I have tested the Notify.py with the pover:// string to confirm it is correct and working and my test notification was sent and received, so I am kind of at a loss. Any ideas?

**Comment by caronc** [comment]
If it works from the command line then it could be a permission issue.  Are you using Linux? I haven't tested the scripts i wrote at all with _nzbget-17_.  It's possible there is something new introduced in that version that I don't handle properly.  I'll try to upgrade my machine at home tonight and keep you posted.

If you fall back to an earlier version, does it work again?

**Comment by CastawayEngineer** [comment]
I did try setting permissions to 777 for kicks with no success. I figured that maybe the case, I will see if I can roll-back nzbget, test, and report back.

**Comment by caronc** [comment]
Great, please keep me posted on your rollback! On a side note, I pinged @hugbug [in his support forum here](http://forum.nzbget.net/viewtopic.php?f=3&t=2566) for any additional feedback he might have.

There is also another thread open on his forum that describes a _similar_ issue to what you're experiencing [here](http://forum.nzbget.net/viewtopic.php?f=3&t=2565). So it's possible you're not alone with this problem. Are other scripts impacted in your case? Or just the Notify.py?
Can you see it correctly from the GUI (it's configuration?).  Or is it even missing from there?

One last note worth mentioning; it may be your NZBGet configuration file (it's possible it's corrupt) or NZBGet is having a hard time parsing it.  Try backing it up and just starting from scratch.  I realize htis is a horrible pain, but if it doesn't work, just roll back with your backup anyway (no harm done).

Good luck

**Comment by caronc** [comment]
It seems to work for me. Have a look at the 2 links I provided to his forum. There are some more suggestions there that might help.

**Comment by caronc** [comment]
Hey, I just wanted to follow up with you on this ticket to see if it's worth closing? Did you ever figure out your issue?

**Comment by caronc** [comment]
Will close for now since we're past a 2 week mark of silence. :)  Feel free to comment if you're still having the issue and I can re-open the case.
