### ISSUE TITLE
Not saving config

### ISSUE THREAD

**Issue by barbequesauce** [caronc/nzb-notify#44]
Hi - just discovered this, great tool- thank you for writing it!

Small issue with nzbget - everything works, except my config doesn’t save. After reload the options switch back. I can’t figure out where the config file is that the settings are being read from so I can check permissions?

**Comment by caronc** [comment]
Your issue is more specific to NZBGet unfortunately.  When you save your configuration file for Subliminal, it saves to the same configuration file that everything else is saved in.

What operating system are you using and what version of NZBGet?

**Comment by barbequesauce** [comment]
Yeah sorry I figured it out late last night - the settings were being saved in the nzbget.conf file.

There's a separate bug in v20 where it appends config changes to the end of the config file (meaning you may have the same setting specified multiple times). Good news is that it is appending, and the file is read beginning-to-end (so the last one takes precedence). Bad news is that I now have a 47k line config...
