### ISSUE TITLE
Notify: NZBParse - NZB-File is missing

### ISSUE THREAD

**Issue by W13N3N** [caronc/nzb-notify#50]
I recently did a clean setup of Notify.py. Since i'm getting the following Warning Message in NZBGET "Notify: NZBParse - NZB-File is missing"

Before i never saw this message. Does someone have an idea how to get rid of this warning message?

Some history;
I'm using NZBTOMEDIA and Notify in combination with NZBGET. Lately NZBTOMEDIA added a cleanup script within there process which also deleted the Notify folders/files. Therefore i created subfolders within the scripts folder of NZBGET and so split both scripts. Since i'm having the above issue (more a warning messange ;-))

**Comment by caronc** [comment]
Did you change/upgrade any other scripts recently? Also what order are you processing this specific Post Process script (NZB-Notify)?  Try bumping the order it gets used to the front of the processing queue; more importantly make sure you run this script before NZBToMedia kicks in and does it's thing.  You can control this from the NZBGet settings page.

In your situation, the NZB-File or the RSS Feed reference for your download was removed (or became inaccessible) prior to this script executed.  At the end of the day it's not a big deal; but i can respect that it might be annoying you if it never did it before.  :slightly_smiling_face:

**Comment by W13N3N** [comment]
@caronc  thanks for your quick reply!

After updating my NZBToMedia scripts a ran into some different issues. After troubleshooting i also found out the notify.py script i was using was old and therefore also updated that one. So to exactly find out which update exactly is causing the new warning message is hard to find out. (it's possible but takes to much time ;-) )

I've did some testing and when i move the Notify script before NZBToMedia then the warning doesn't appear.  So i guess maybe NZBToMedia removes the nzb file and therefor Notify gave the warning.

The warning is gone so i'm happy now!! Thanks for the tip!
