### ISSUE TITLE
"ImportError: No module named nzbget" when using with sabnzbd

### ISSUE THREAD

**Issue by tehniemer** [caronc/nzb-notify#59]
I'm getting the following error running this script in sabnzbd

```
 Notification script returned exit code 1 and output "Traceback (most recent call last):
  File "/config/scripts/Notify.py", line 175, in <module>
    from nzbget import SCRIPT_MODE
ImportError: No module named nzbget
"
```

I have it calling the sabnzbd-notify.py script.

**Comment by caronc** [comment]
I'm not sure what OS you're running, but basically you're just missing the dependencies needed to use nzb-notify.  
```bash
# Run this from the directory you cloned nzb-notify into; this will haul in your
# missing dependencies:
pip install -r requirements.txt
```

**Comment by tehniemer** [comment]
It's running in Docker.

**Comment by caronc** [comment]
Have a look at #53.  It seems like it's your exact error; there are a few suggestions in it at the bottom that will probably fix you right up! :slightly_smiling_face:

**Comment by tehniemer** [comment]
OK thanks, I'll give that a try.

**Comment by caronc** [comment]
Did you have any luck?  If so, do you mind if I close this ticket off? Otherwise please keep me posted as i can still try to be of more assistance :slightly_smiling_face:

**Comment by tehniemer** [comment]
No, I have sabnzbd running in docker and this is the error I get 

'''
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"pip\": executable file not found in $PATH": unknown
'''

I'm guessing the image I'm using doesn't have the right things installed.

**Comment by caronc** [comment]
Sorry to hear that!  Could you share your Dockerfile with me?  Maybe we can just adjust it to fix your issue.

**Comment by caronc** [comment]
Just to add to this, I missed your comment about pip being missing. Try adding this first:
```bash
apt-get install python-pip
```
I'll update the sample Docker container reference comment (above) too to include this.

**Comment by tehniemer** [comment]
Thanks for the guidance, I forked the linuxserver.io repository and ended up with this as my dockerfile

```
FROM lsiobase/ubuntu:bionic

# set version label
ARG BUILD_DATE
ARG VERSION
ARG SABNZBD_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="sparklyballs"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config" \
PYTHONIOENCODING=utf-8

RUN \
 echo "***** install gnupg ****" && \
 apt-get update && \
 apt-get install -y \
        gnupg && \
 echo "***** add sabnzbd repositories ****" && \
 apt-key adv --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 0x98703123E0F52B2BE16D586EF13930B14BB9F05F && \
 echo "deb http://ppa.launchpad.net/jcfp/nobetas/ubuntu bionic main" >> /etc/apt/sources.list.d/sabnzbd.list && \
 echo "deb-src http://ppa.launchpad.net/jcfp/nobetas/ubuntu bionic main" >> /etc/apt/sources.list.d/sabnzbd.list && \
 echo "deb http://ppa.launchpad.net/jcfp/sab-addons/ubuntu bionic main" >> /etc/apt/sources.list.d/sabnzbd.list && \
 echo "deb-src http://ppa.launchpad.net/jcfp/sab-addons/ubuntu bionic main" >> /etc/apt/sources.list.d/sabnzbd.list && \
 echo "**** install packages ****" && \
 if [ -z ${SABNZBD_VERSION+x} ]; then \
	SABNZBD="sabnzbdplus"; \
 else \
	SABNZBD="sabnzbdplus=${SABNZBD_VERSION}"; \
 fi && \
 apt-get update && \
 apt-get install -y \
	p7zip-full \
	par2-tbb \
	python-pip \
	${SABNZBD} \
	unrar \
	unzip && \
 pip install --no-cache-dir \
	apprise \
	chardet \
	pynzb \
	requests \
	sabyenc \
	setuptools \
	pynzbget \
	six && \		
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
	/tmp/* \
	/var/lib/apt/lists/* \
	/var/tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8080 9090
VOLUME /config /downloads /incomplete-downloads
```

The test notification was sent, so it seems to be working and nothing else has broken....yet.

**Comment by caronc** [comment]
That's great to hear! Also, thank you for sharing your solution too!
