### ISSUE TITLE
notify does not work with the latest Linuxserver.io/docker

### ISSUE THREAD

**Issue by keppo070** [caronc/nzb-notify#61]
Is there a way to let this script work with the latest linuxserver/nzbget docker

Fri Jun 26 18:03:10 2020        ERROR   Script Notify.py with command TestServers failed (terminated with unknown status)
Fri Jun 26 18:14:41 2020        INFO    Executing script Notify.py with command TestServers
Fri Jun 26 18:14:41 2020        INFO    Notify: Traceback (most recent call last):
Fri Jun 26 18:14:41 2020        INFO    Notify:   File "/downloads/scripts/Notify.py", line 410, in <module>
Fri Jun 26 18:14:41 2020        INFO    Notify:     from nzbget import SCRIPT_MODE
Fri Jun 26 18:14:41 2020        INFO    Notify:   File "/downloads/scripts/Notify/nzbget/__init__.py", line 23, in <module>
Fri Jun 26 18:14:41 2020        INFO    Notify:     from .ScriptBase import *
Fri Jun 26 18:14:41 2020        INFO    Notify:   File "/downloads/scripts/Notify/nzbget/ScriptBase.py", line 959
Fri Jun 26 18:14:41 2020        INFO    Notify:     makedirs(self.tempdir, 0700)
Fri Jun 26 18:14:41 2020        INFO    Notify:                               ^
Fri Jun 26 18:14:41 2020        INFO    Notify: SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
Fri Jun 26 18:14:41 2020        ERROR   Script Notify.py with command TestServers failed (terminated with unknown status)

**Comment by caronc** [comment]
Hmm basically it's because you're using Python 3 and using an older version of nzb-notify.

The current version pulls in ScriptBase.py from pypy (via [pynzbget](https://pypi.org/project/pynzbget/)) which is compatible with Python v3.

I think the  Linuxserver.io/docker needs to be updated to do a `pip install pynzbet` and retrieve the latest version of `nzb-notify` and you should be fine.

**Comment by keppo070** [comment]
Yes, that did the trick. Thank you
