### ISSUE TITLE
module named six is missing

### ISSUE THREAD

**Issue by ljflowers90** [caronc/nzb-notify#62]
ive been trying for the past few days to get this working on nzbget 

this is all on ubuntu seedbox

Wed Jul  1 23:32:58 2020	WARNING	Notify: Fixing permissions for/home1/ljflowers20/Nzbget/scripts/nzb-notify-master/Notify.py
Wed Jul  1 23:32:58 2020	INFO	Notify: Traceback (most recent call last):
Wed Jul  1 23:32:58 2020	INFO	Notify:   File "/home1/ljflowers20/Nzbget/scripts/nzb-notify-master/Notify.py", line 169, in <module>
Wed Jul  1 23:32:58 2020	INFO	Notify:     import six
Wed Jul  1 23:32:58 2020	INFO	Notify: ModuleNotFoundError: No module named 'six'
Wed Jul  1 23:32:58 2020	ERROR	Script nzb-notify-master/Notify.py with command TestServers failed (terminated with unknown status)
Wed Jul  1 23:36:30 2020	INFO	Executing script nzb-notify-master/Notify.py with command TestServers
Wed Jul  1 23:36:30 2020	INFO	Notify: Traceback (most recent call last):
Wed Jul  1 23:36:30 2020	INFO	Notify:   File "/home1/ljflowers20/Nzbget/scripts/nzb-notify-master/Notify.py", line 169, in <module>
Wed Jul  1 23:36:30 2020	INFO	Notify:     import six
Wed Jul  1 23:36:30 2020	INFO	Notify: ModuleNotFoundError: No module named 'six'
Wed Jul  1 23:36:30 2020	ERROR	Script nzb-notify-master/Notify.py with command TestServers failed (terminated with unknown status)
Wed Jul  1 23:40:08 2020	INFO	Executing script nzb-notify-master/Notify.py with command TestServers
Wed Jul  1 23:40:08 2020	INFO	Notify: Traceback (most recent call last):
Wed Jul  1 23:40:08 2020	INFO	Notify:   File "/home1/ljflowers20/Nzbget/scripts/nzb-notify-master/Notify.py", line 169, in <module>
Wed Jul  1 23:40:08 2020	INFO	Notify:     import six
Wed Jul  1 23:40:08 2020	INFO	Notify: ModuleNotFoundError: No module named 'six'
Wed Jul  1 23:40:08 2020	ERROR	Script nzb-notify-master/Notify.py with command TestServers failed (terminated with unknown status)
Wed Jul  1 23:40:17 2020	INFO	Reloading...
Wed Jul  1 23:40:18 2020	INFO	nzbget 21.0 server-mode
Wed Jul  1 23:40:30 2020	INFO	Executing script nzb-notify-master/Notify.py with command TestServers
Wed Jul  1 23:40:30 2020	INFO	Notify: Traceback (most recent call last):
Wed Jul  1 23:40:30 2020	INFO	Notify:   File "/home1/ljflowers20/Nzbget/scripts/nzb-notify-master/Notify.py", line 169, in <module>
Wed Jul  1 23:40:30 2020	INFO	Notify:     import six
Wed Jul  1 23:40:30 2020	INFO	Notify: ModuleNotFoundError: No module named 'six'
Wed Jul  1 23:40:30 2020	ERROR	Script nzb-notify-master/Notify.py with command TestServers failed (terminated with unknown status)

**Comment by caronc** [comment]
You need to also make sure you have the scripts dependencies installed (found in the **requirements.txt** file).  See the [installation instructions](https://github.com/caronc/nzb-notify#installation-instructions). But in short:
```bash
 # Pull in dependencies:
pip install -r requirements.txt
```

That will include your missing `six` module. :slightly_smiling_face:

**Comment by caronc** [comment]
I will close this ticket off if you don't have any questions! Feel free to open another or ask more here if you need!
