### ISSUE TITLE
Does this only work in Python2?

### ISSUE THREAD

**Issue by nuentes** [caronc/nzb-notify#63]
pip is not installed on my Ubuntu MATE server, however I have pip3. so I ran

`pip3 install -r requirements.txt`

I'm getting the standard message I've seen you reply about:

```
Executing script nzb-notify-master/Notify.py with command TestServers
Notify: Traceback (most recent call last):
Notify:   File "/opt/nzbget/scripts/nzb-notify-master/Notify.py", line 175, in <module>
Notify:     from nzbget import SCRIPT_MODE
Notify: ImportError: No module named nzbget
Script nzb-notify-master/Notify.py with command TestServers failed (terminated with unknown status)
```

Quick side note - since you know that this is caused by the requirements not being installed, would it make sense to call this out in the failure log? Moving on - I ensured that the requirements are installed, however I'm still getting this error message. Any idea what's going on? Is this because I installed with pip3? The installation instructions say "Ensure you have Python v2.7 or later installed onto your system.", and I believe I have met that requirement.

**Comment by caronc** [comment]
Hi,

I'm so sorry it took so long for me to get back to you. I'm not sure how i missed this bug report.  the nzbget library should be available, it's on PyPi even.  You could just try something like:
```bash
pip3 install pynzbget
```

**Comment by caronc** [comment]
Hi, it's been a while. I'm going to presume your question was answered? If not feel free to leave a comment here or open another ticket! :slightly_smiling_face:
