### ISSUE TITLE
SABnzbd Icon/Images do not work for some providers

### ISSUE THREAD

**Issue by caronc** [caronc/nzb-notify#65]
Notification Services can get images associated with the notification you post by 2 possible ways:
1. A remote URL (such as) https://sabnzbd.org/images/icons/apple-touch-icon-76x76-precomposed.png
2. A local reference (bundled with nzb-notify).

It's the latter (option 2) that is missing for SABnzb users.  So all notification services that would otherwise attach an image stored locally... well there just isn't one.

Refs observation found by @fragande (#64) with Growl Plugin, but this bug extends to many more services.

**Comment by caronc** [comment]
@fragande,

You should be good to go; you just need to use the updated NZB-Notify packages pushed to the master branch just now.

Both local and remote images have been updated.
You can compare the two image folders (these are themes):
* general: https://github.com/caronc/nzb-notify/tree/master/Notify/apprise-theme/general
* sabnzbd: https://github.com/caronc/nzb-notify/tree/master/Notify/apprise-theme/sabnzbd

I searched Google and gathered a few larger images of sabnzbd and shrunk them to fit their respected sizes; but at the end of the day they're all the same image.  You'd have a nicer experience if we started tweaking the `warning` from the `failure`, etc  But for now at least there is a baseline set up and it continues to use the SABnzbd logo everywhere (locally now too which targets this issue specifically).

**Comment by fragande** [comment]
@caronc,

Can confirm that the sabnzbd icon now is displayed correctly, thank you :)

**Comment by caronc** [comment]
Awesome! I'm going to close off this issue. Let me know if you have any more problems on this or feel free to open a new ticket. 🙂
