### ISSUE TITLE
Unable to receive notifications vis Pushover in NZBGet

### ISSUE THREAD

**Issue by cuckys** [caronc/nzb-notify#66]
:mega: **Notification Service(s) Impacted**
**Pushover**

:beetle: **Describe the bug**
Unable to receive push notification via Pushover.

:bulb: **Screenshots and Logs**
```
INFO | Fri Aug 21 2020 01:46:17 | Notify: [DEBUG] Exiting with return code: 93
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(config) INCLUDEIMAGE="no"
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(config) SERVERS="pover://xxx@xxx"
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(config) ONQUEUE="yes"
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(config) INCLUDEIMAGE="no"
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(default) BODY=None
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(default) TITLE=None
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] get(config) SERVERS="pover://xxx@xxx"
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] Process directory is missing: /mnt/stuff/xxx/NZBGet/intermediate/xxx
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] OS: FreeBSD 11.3-RELEASE-p11
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] Python v3.7.8
INFO | Fri Aug 21 2020 01:46:15 | Notify: [DEBUG] Script Mode: queue
```

:computer: **Your System Details:**
 - OS: FreeBSD 11.3-RELEASE-p11
 - Python Version: Python v3.7.8

:crystal_ball: **Additional context**
Note that I can receive the test notification successfully.

**Comment by caronc** [comment]
The logs you share show for the **OnQueue** mode.  This will only trigger if you've set your configuration to notify you in this instance.

if you go into your server settings and then the **Notify** Plugin options, verify you're set up to send a notification **OnQueue** if this is what you want.

Also, make sure you set the **Notify** script to run early in the *Ordering* for best results.

Let me know how it goes

**Comment by caronc** [comment]
How did things go; were you able to figure this out?

**Comment by caronc** [comment]
I'm closing this issue as i have not heard back from you in a while now.  Please feel free to comment here or open a new ticket if you're still having problems.
