### ISSUE TITLE
Script start failed

### ISSUE THREAD

**Issue by mouzzampk2014** [caronc/nzb-notify#70]
Hi, seem like I am missing something. I entered my Pushover information but when I click on Test Server Configuration, this message comes up `Script start failed`

I am runnung linuxserver/nzbget:latest

Thanks

**Comment by mouzzampk2014** [comment]
After restarting the nzbget and Test Server Configuration this is the message comping up now ```
Executing script nzb-notify/Notify.py with command TestServers
Notify: Fixing permissions for/shared/downloads/usenet/scripts/nzb-notify/Notify.py
Notify: Traceback (most recent call last):
Notify:   File "/shared/downloads/usenet/scripts/nzb-notify/Notify.py", line 169, in <module>
Notify:     import six
Notify: ModuleNotFoundError: No module named 'six'
Script nzb-notify/Notify.py with command TestServers failed (terminated with unknown status)
```

**Comment by caronc** [comment]
Your issue seems tied to #62, #66, and #69 . There appears to be something wrong with the latest container built for nzbget and linuxserver.  You may need to request that they rebuild that instance.

You could try just satisfying the needs of the container by connecting to it and running:
```bash
pip install six
```

That might work for you! :crossed_fingers:

**Comment by mouzzampk2014** [comment]
> Your issue seems tied to #62, #66, and #69 . There appears to be something wrong with the latest container built for nzbget and linuxserver. You may need to request that they rebuild that instance.
> 
> You could try just satisfying the needs of the container by connecting to it and running:
> 
> ```shell
> pip install six
> ```
> 
> That might work for you! 🤞

Thank you so much. I will update you later tonight.

Thanks again for quick reply. I will raise this with linuxserver too so they can add the missing dependencies. Thanks again

**Comment by caronc** [comment]
Hi,

Are you okay if I close this ticket?

**Comment by mouzzampk2014** [comment]
Hi @caronc I'm really sorry for left this open. This was resolved same day. Thank you so much
