### ISSUE TITLE
Issue with SABnzbd on Mac

### ISSUE THREAD

**Issue by kilgil27** [caronc/nzb-notify#75]
:beetle: **Describe the bug**
Getting the following error when trying to run with SABnzbd running on a Mac:
Notification script returned exit code 1 and output "Traceback (most recent call last): File "/Users/killian/Scripts/nzb-notify-0.9.4/Notify.py", line 174, in <module> from nzbget import SCRIPT_MODE ImportError: No module named nzbget "

:computer: **Your System Details:**
 - OS: macOS Big Sur
 - Python Version: Python 3.10.0

:crystal_ball: **Additional context**
running the requirements again says all the requirements are met. I can run a test through terminal with the following and it goes through fine to Telegram
python sabnzbd-notify.py complete 'Hello' 'Worldp' tgram://{bot_ID}/{chat_ID}

**Comment by caronc** [comment]
Seems really similar to #72. Are you using some container or packaged product? 

You could try running the following in your container to see if it helps:
```bash
pip install pynzbget
```

**Comment by kilgil27** [comment]
Yea I was reading through that, seems very similar but this is just a regular SAB install on a Mac mini, no containers or anything

running pip install pynzbget gets the following:

Requirement already satisfied: pynzbget in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.6.4)
Requirement already satisfied: lxml>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pynzbget) (4.6.4)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pynzbget) (1.16.0)

**Comment by kilgil27** [comment]
you know I just tried it on a PC I had setup previously that did have notifications working, and got a similar error:

 Notification script returned exit code 1 and output "Traceback (most recent call last): File "C:\Tools\nzb-notify\Notify.py", line 159, in <module> from nzbget import SCRIPT_MODE ModuleNotFoundError: No module named 'nzbget' "

wonder if something changed or I'm doing something wrong...

**Comment by caronc** [comment]
Did you ever get this resolved?  I can tell you with certainty that if you're not able to run this script, it's possibly due to your Python installation in windows. For the specific error you're getting; make sure you run:
```bash
pip install pynzbget
```

**Comment by farberm** [comment]
I am getting the same error. I have python 3.10.2 installed and set as the default. Not sure what the issue is. I even tried to resolve using suggestion in Issue #72 by changing default to python3. Still same error.??? (except line 174)

**Comment by caronc** [comment]
There is something wrong with your environment unfortunately; this isn't an issue with the script.
