### ISSUE TITLE
Issue with SABnzbd and Docker

### ISSUE THREAD

**Issue by kilgil27** [caronc/nzb-notify#76]
:question: **Question**

I installed sab in unraid with docker, and I'm having issues getting nzb-notify to run. I can install the requirements and everything, but when I go to run the script, I get the following error: 1560 - ERROR - The engine /config/scripts/nzb-notify-master/Notify.py was not found!

I think maybe it's an issue with the drive mapping. but when I open the sab console and navigate to the scripts folder, all the correct files show in there

Nevermind... just needed to chmod notify.py and sabnzbd-notify.py to be executable. You can close this thanks!

**Comment by caronc** [comment]
I'm glad you figured it out! :slightly_smiling_face:
