### ISSUE TITLE
Create new release 

### ISSUE THREAD

**Issue by Safihre** [caronc/nzb-notify#79]
:question: **Question**
As we are now redirecting SABnzbd users to here for their notification needs, we do need an official nzb-notify release that includes the pause/resume support.
I don't think the latest official release includes that?
For example our "official" Docker from Linuxserver.io now includes nzb-notify, but does so based on official release: https://github.com/linuxserver/docker-sabnzbd/commit/477b9125e102630c5f838dcd37e8b886837100d9

And probably then script deserves a 1.0.0 release, seems pretty stable to me 😊

Thanks!

**Comment by caronc** [comment]
Sure, are `pause` and `resume` just a few extra keys i can add to the existing mappings in the script?

I'll try to look into this tomorrow (today is pretty much off the table)

**Comment by Safihre** [comment]
You already implemented the changes a while ago, you just haven't made a release since :)

**Comment by oztrich** [comment]
Hi, I've just picked up the message to switch from my existing Pushover notification set up in SABnzbd to use nzb-notify instead.

Is there a way to configure the priority of notifications in the same way the current Pushover config works?  I have a variety of different notification levels set currently, and this determines whether the alert will arrive silently or trigger some audible (or other) warning.  At the moment I can only see everything coming through with the same priority using nzb-notify.

Thanks!

**Comment by caronc** [comment]
@Safihre: Release v1.0.0 created! :+1: 
@oztrich: Unfortunately no; you would set up your notification configuration the way you want, but then use SABnzbd to customize which services you want to be notified for.
