### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mohitjoshi155** [caronc/nzb-notify#85]
![Screenshot_20220424-142640_Browser](https://user-images.githubusercontent.com/58655292/164968748-090be284-33af-4772-8422-ee8572e971fe.jpg)

Notify: Failed to send Telegram notification to 529023895: Bad Request: can't parse entities: Unsupported start tag "ul" at byte offset 134, error=400.

i keep getting errors like this

**Comment by caronc** [comment]
This was accidentally introduced in the latest version of Apprise while trying to address other formatting requests. There is a fix coming [here](https://github.com/caronc/apprise/pull/575) hopefully this week sometime. I'm not available to work on it today which is unfortunately delaying the process a bit. If you're good with Python, feel free to have a look and add any thoughts, or code changes. Alternatively, see if it offers any improvements for you.

Another alternative is to just use the previous version of Apprise for the next few days:
`pip install apprise == 0.9.7`

**Comment by caronc** [comment]
Another thing you can do is use the latest version, but just put `?format=markdown` at the end of your Telegram (`tgram://`) Apprise URL

**Comment by mohitjoshi155** [comment]
pip install apprise == 0.9.7 worked perfectly for me thanks
