### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by JBHorne2** [caronc/nzb-notify#95]
Getting this error when testing the sabnzbd-notify.py script.

`root@sabnzbd:/usr/share/sabnzbdplus/sabnzbd/scripts# python sabnzbd-notify.py startup 'Hello' 'World' hassio://test.local
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/scripts/Notify.py", line 169, in <module>
    import six
ImportError: No module named six
root@sabnzbd:/usr/share/sabnzbdplus/sabnzbd/scripts# pip list
Package             Version
------------------- --------------
apprise             1.3.0
babelfish           0.5.4
certifi             2020.6.20
cffi                1.15.1
chardet             4.0.0
Cheetah3            3.2.6
cheroot             9.0.0
CherryPy            8.9.1
click               8.1.3
configobj           5.0.6
cryptography        3.3.2
dbus-python         1.2.16
distro-info         1.0
feedparser          5.2.1
guessit             3.2.0
httplib2            0.18.1
idna                2.10
importlib-metadata  6.3.0
jaraco.classes      3.2.3
jaraco.collections  3.8.0
jaraco.context      4.2.0
jaraco.functools    3.0.0
jaraco.text         3.8.1
lxml                4.9.2
Markdown            3.4.3
more-itertools      4.2.0
notify2             0.3
oauthlib            3.2.2
pip                 20.3.4
portend             2.6
puremagic           1.14
pycparser           2.21
pycurl              7.43.0.6
PyGObject           3.38.0
pynzbget            0.6.4
pyOpenSSL           20.0.1
PySimpleSOAP        1.16.2
PySocks             1.7.1
python-apt          2.2.1
python-dateutil     2.8.1
python-debian       0.1.39
python-debianbts    3.1.0
pytz                2021.1
PyYAML              6.0
rebulk              3.0.1
reportbug           7.10.3+deb11u1
repoze.lru          0.7
requests            2.25.1
requests-oauthlib   1.3.1
Routes              2.5.1
sabyenc3            5.4.3
setuptools          52.0.0
sgmllib3k           1.0.0
simplejson          3.17.2
six                 1.16.0
tempora             2.1.1
toposort            1.6
ujson               4.0.2
unattended-upgrades 0.1
urllib3             1.26.5
WebOb               1.8.6
wheel               0.34.2
zc.lockfile         2.0
zipp                3.15.0
root@sabnzbd:/usr/share/sabnzbdplus/sabnzbd/scripts# `

**Comment by caronc** [comment]
Seems like it might be an environment issue as `six` is identified in that list. You could try running the Notify.py script manually to see if you get the same error.

Make sure you're using Python 3, `pip3`. In the past, `pip` mapped to Python 2

**Comment by caronc** [comment]
closing issue after not hearing back
